// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUn4YH0HDF0hOIrLtQnNiqHI7B6_nVpJQ',
    appId: '1:129569496712:web:c274946223347779e9c93d',
    messagingSenderId: '129569496712',
    projectId: 'tottal-x',
    authDomain: 'tottal-x.firebaseapp.com',
    storageBucket: 'tottal-x.firebasestorage.app',
    measurementId: 'G-THZQTF5E5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMQIQ5CZ7IHLoZz40rn1VtCPmghoZ7T14',
    appId: '1:129569496712:android:bc73110069e8464be9c93d',
    messagingSenderId: '129569496712',
    projectId: 'tottal-x',
    storageBucket: 'tottal-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVdVK9Yp7VHASPu93-XPNUve6W5SK4IPM',
    appId: '1:129569496712:ios:8c400161d343c48fe9c93d',
    messagingSenderId: '129569496712',
    projectId: 'tottal-x',
    storageBucket: 'tottal-x.firebasestorage.app',
    iosBundleId: 'com.example.tottalx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVdVK9Yp7VHASPu93-XPNUve6W5SK4IPM',
    appId: '1:129569496712:ios:8c400161d343c48fe9c93d',
    messagingSenderId: '129569496712',
    projectId: 'tottal-x',
    storageBucket: 'tottal-x.firebasestorage.app',
    iosBundleId: 'com.example.tottalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUn4YH0HDF0hOIrLtQnNiqHI7B6_nVpJQ',
    appId: '1:129569496712:web:f1fa56cd2621727ae9c93d',
    messagingSenderId: '129569496712',
    projectId: 'tottal-x',
    authDomain: 'tottal-x.firebaseapp.com',
    storageBucket: 'tottal-x.firebasestorage.app',
    measurementId: 'G-2F3GT5Q8CW',
  );

}